version: '3'

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesResolvers.myresolver.acme.tlsChallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=d.vasilev@innopolis.university"
      - "--certificatesResolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt/acme.json:/letsencrypt/acme.json"
    networks:
      - web
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.routers.web.rule=Host(`alumni-portal.ru`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.rule=Host(`traefik.alumni-portal.ru`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"

  auth-service:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    image:
      danyadrakon/auth-service:latest
    volumes:
      - ./shared:/app/shared
    environment:
      - DB=${DB}
      - SECRET=${SECRET}
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - OPENAI_KEY=${OPENAI_KEY}
    labels:
      - "traefik.enable=true"  # Enable Traefik for this service
      - "traefik.http.routers.auth-service.rule=Host(`api.alumni-portal.ru`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth-service.entrypoints=websecure"  # Use HTTPS entry point
      - "traefik.http.routers.auth-service.tls=true"
      - "traefik.http.routers.auth-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.auth-service-redirect-https.redirectscheme.scheme=https"  # Redirect HTTP to HTTPS
      - "traefik.http.routers.auth-service.middlewares=auth-service-redirect-https"  # Apply HTTPS redirection middleware
      - "traefik.http.middlewares.auth-service-cors.headers.accessControlAllowOriginList=https://alumni-inno.netlify.app"  # CORS settings
      - "traefik.http.middlewares.auth-service-cors.headers.accessControlAllowMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS"
      - "traefik.http.middlewares.auth-service-cors.headers.accessControlAllowHeaders=Content-Type,Authorization"
      - "traefik.http.middlewares.auth-service-cors.headers.accessControlExposeHeaders=Content-Length"
      - "traefik.http.middlewares.auth-service-cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.routers.auth-service.middlewares=auth-service-cors"  # Apply CORS middleware
      - "traefik.http.services.auth-service.loadbalancer.server.port=8081"  # Service port
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  project-service:
    build:
      context: .
      dockerfile: ProjectService/Dockerfile
    image:
      danyadrakon/project-service:latest
    volumes:
      - ./shared:/app/shared
    environment:
      - DB=${DB}
      - SECRET=${SECRET}
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - OPENAI_KEY=${OPENAI_KEY}
    labels:
      - "traefik.enable=true"  # Enable Traefik for this service
      - "traefik.http.routers.project-service.rule=Host(`api.alumni-portal.ru`) && PathPrefix(`/projects`)"
      - "traefik.http.routers.project-service.entrypoints=websecure"  # Use HTTPS entry point
      - "traefik.http.routers.project-service.tls=true"
      - "traefik.http.routers.project-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.project-service-redirect-https.redirectscheme.scheme=https"  # Redirect HTTP to HTTPS
      - "traefik.http.routers.project-service.middlewares=project-service-redirect-https"  # Apply HTTPS redirection middleware
      - "traefik.http.middlewares.project-service-cors.headers.accessControlAllowOriginList=https://alumni-inno.netlify.app"  # CORS settings
      - "traefik.http.middlewares.project-service-cors.headers.accessControlAllowMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS"
      - "traefik.http.middlewares.project-service-cors.headers.accessControlAllowHeaders=Content-Type,Authorization"
      - "traefik.http.middlewares.project-service-cors.headers.accessControlExposeHeaders=Content-Length"
      - "traefik.http.middlewares.project-service-cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.routers.project-service.middlewares=project-service-cors"  # Apply CORS middleware
      - "traefik.http.services.project-service.loadbalancer.server.port=8085"  # Service port
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  filtering-service:
    build:
      context: .
      dockerfile: FilteringService/Dockerfile
    image:
      danyadrakon/filtering-service:latest
    volumes:
      - ./shared:/app/shared
    environment:
      - API_KEY=${API_KEY}
      - OPENAI_KEY=${OPENAI_KEY}
    networks:
      - web
    ports:
      - "50051:50051"

  requests-service:
    build:
      context: .
      dockerfile: AdditionalRequestService/Dockerfile
    image:
      danyadrakon/requests-service:latest
    volumes:
      - ./shared:/app/shared
    environment:
      - DB=${DB}
      - SECRET=${SECRET}
      - PORT=${PORT}
    labels:
      - "traefik.enable=true"  # Enable Traefik for this service
      - "traefik.http.routers.requests-service.rule=Host(`api.alumni-portal.ru`) && PathPrefix(`/requests`)"
      - "traefik.http.routers.requests-service.entrypoints=websecure"  # Use HTTPS entry point
      - "traefik.http.routers.requests-service.tls=true"
      - "traefik.http.routers.requests-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.requests-service-redirect-https.redirectscheme.scheme=https"  # Redirect HTTP to HTTPS
      - "traefik.http.routers.requests-service.middlewares=requests-service-redirect-https"  # Apply HTTPS redirection middleware
      - "traefik.http.middlewares.requests-service-cors.headers.accessControlAllowOriginList=https://alumni-inno.netlify.app"  # CORS settings
      - "traefik.http.middlewares.requests-service-cors.headers.accessControlAllowMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS"
      - "traefik.http.middlewares.requests-service-cors.headers.accessControlAllowHeaders=Content-Type,Authorization"
      - "traefik.http.middlewares.requests-service-cors.headers.accessControlExposeHeaders=Content-Length"
      - "traefik.http.middlewares.requests-service-cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.routers.requests-service.middlewares=requests-service-cors"  # Apply CORS middleware
      - "traefik.http.services.requests-service.loadbalancer.server.port=8082"  # Service port
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  donation-service:
    build:
      context: .
      dockerfile: DonationService/Dockerfile
    image:
      danyadrakon/donation-service:latest
    volumes:
      - ./shared:/app/shared
    environment:
      - DB=${DB}
      - SECRET=${SECRET}
      - PORT=${PORT}
    labels:
      - "traefik.enable=true"  # Enable Traefik for this service
      - "traefik.http.routers.donation-service.rule=Host(`api.alumni-portal.ru`) && PathPrefix(`/donation`)"
      - "traefik.http.routers.donation-service.entrypoints=websecure"  # Use HTTPS entry point
      - "traefik.http.routers.donation-service.tls=true"
      - "traefik.http.routers.donation-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.donation-service-redirect-https.redirectscheme.scheme=https"  # Redirect HTTP to HTTPS
      - "traefik.http.routers.donation-service.middlewares=donation-service-redirect-https"  # Apply HTTPS redirection middleware
      - "traefik.http.middlewares.donation-service-cors.headers.accessControlAllowOriginList=https://alumni-inno.netlify.app"  # CORS settings
      - "traefik.http.middlewares.donation-service-cors.headers.accessControlAllowMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS"
      - "traefik.http.middlewares.donation-service-cors.headers.accessControlAllowHeaders=Content-Type,Authorization"
      - "traefik.http.middlewares.donation-service-cors.headers.accessControlExposeHeaders=Content-Length"
      - "traefik.http.middlewares.donation-service-cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.routers.donation-service.middlewares=donation-service-cors"  # Apply CORS middleware
      - "traefik.http.services.donation-service.loadbalancer.server.port=8083"  # Service port
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  event-service:
    build:
      context: .
      dockerfile: EventService/Dockerfile
    image:
      danyadrakon/event-service:latest
    volumes:
      - ./shared:/app/shared
    environment:
      - DB=${DB}
      - SECRET=${SECRET}
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - OPENAI_KEY=${OPENAI_KEY}
    labels:
      - "traefik.enable=true"  # Enable Traefik for this service
      - "traefik.http.routers.event-service.rule=Host(`api.alumni-portal.ru`) && PathPrefix(`/events`)"
      - "traefik.http.routers.event-service.entrypoints=websecure"  # Use HTTPS entry point
      - "traefik.http.routers.event-service.tls=true"
      - "traefik.http.routers.event-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.event-service-redirect-https.redirectscheme.scheme=https"  # Redirect HTTP to HTTPS
      - "traefik.http.routers.event-service.middlewares=event-service-redirect-https"  # Apply HTTPS redirection middleware
      - "traefik.http.middlewares.event-service-cors.headers.accessControlAllowOriginList=https://alumni-inno.netlify.app"  # CORS settings
      - "traefik.http.middlewares.event-service-cors.headers.accessControlAllowMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS"
      - "traefik.http.middlewares.event-service-cors.headers.accessControlAllowHeaders=Content-Type,Authorization"
      - "traefik.http.middlewares.event-service-cors.headers.accessControlExposeHeaders=Content-Length"
      - "traefik.http.middlewares.event-service-cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.routers.event-service.middlewares=event-service-cors"  # Apply CORS middleware
      - "traefik.http.services.event-service.loadbalancer.server.port=8084"  # Service port
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  volunteer-service:
    build:
      context: .
      dockerfile: VolunteerService/Dockerfile
    image:
      danyadrakon/volunteer-service:latest
    volumes:
      - ./shared:/app/shared
    environment:
      - DB=${DB}
      - SECRET=${SECRET}
      - PORT=${PORT}
    labels:
      - "traefik.enable=true"  # Enable Traefik for this service
      - "traefik.http.routers.volunteer-service.rule=Host(`api.alumni-portal.ru`) && PathPrefix(`/volunteer`)"
      - "traefik.http.routers.volunteer-service.entrypoints=websecure"  # Use HTTPS entry point
      - "traefik.http.routers.volunteer-service.tls=true"
      - "traefik.http.routers.volunteer-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.volunteer-service-redirect-https.redirectscheme.scheme=https"  # Redirect HTTP to HTTPS
      - "traefik.http.routers.volunteer-service.middlewares=volunteer-service-redirect-https"  # Apply HTTPS redirection middleware
      - "traefik.http.middlewares.volunteer-service-cors.headers.accessControlAllowOriginList=https://alumni-inno.netlify.app"  # CORS settings
      - "traefik.http.middlewares.volunteer-service-cors.headers.accessControlAllowMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS"
      - "traefik.http.middlewares.volunteer-service-cors.headers.accessControlAllowHeaders=Content-Type,Authorization"
      - "traefik.http.middlewares.volunteer-service-cors.headers.accessControlExposeHeaders=Content-Length"
      - "traefik.http.middlewares.volunteer-service-cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.routers.volunteer-service.middlewares=volunteer-service-cors"  # Apply CORS middleware
      - "traefik.http.services.volunteer-service.loadbalancer.server.port=8086"  # Service port
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"