version: '3.7'

services:
  auth-service:
    build:
      context: ./AdditionalRequestService
    ports:
      - "8080:8080"
    depends_on:
      - logstash
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  requests-service:
    build:
      context: ./AuthService
    ports:
      - "8081:8081"
    depends_on:
      - logstash
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.3
    container_name: logstash
    volumes:
      - ./elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=testpassword
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
