// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: filtering_service.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FilteringServiceClient is the client API for FilteringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilteringServiceClient interface {
	GradeDescription(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradeResponse, error)
}

type filteringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilteringServiceClient(cc grpc.ClientConnInterface) FilteringServiceClient {
	return &filteringServiceClient{cc}
}

func (c *filteringServiceClient) GradeDescription(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradeResponse, error) {
	out := new(GradeResponse)
	err := c.cc.Invoke(ctx, "/filteringservice.FilteringService/GradeDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilteringServiceServer is the server API for FilteringService service.
// All implementations must embed UnimplementedFilteringServiceServer
// for forward compatibility
type FilteringServiceServer interface {
	GradeDescription(context.Context, *GradeRequest) (*GradeResponse, error)
	mustEmbedUnimplementedFilteringServiceServer()
}

// UnimplementedFilteringServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFilteringServiceServer struct {
}

func (UnimplementedFilteringServiceServer) GradeDescription(context.Context, *GradeRequest) (*GradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GradeDescription not implemented")
}
func (UnimplementedFilteringServiceServer) mustEmbedUnimplementedFilteringServiceServer() {}

// UnsafeFilteringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilteringServiceServer will
// result in compilation errors.
type UnsafeFilteringServiceServer interface {
	mustEmbedUnimplementedFilteringServiceServer()
}

func RegisterFilteringServiceServer(s grpc.ServiceRegistrar, srv FilteringServiceServer) {
	s.RegisterService(&FilteringService_ServiceDesc, srv)
}

func _FilteringService_GradeDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilteringServiceServer).GradeDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filteringservice.FilteringService/GradeDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilteringServiceServer).GradeDescription(ctx, req.(*GradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilteringService_ServiceDesc is the grpc.ServiceDesc for FilteringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilteringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filteringservice.FilteringService",
	HandlerType: (*FilteringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GradeDescription",
			Handler:    _FilteringService_GradeDescription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "filtering_service.proto",
}
