name: CI/CD Pipeline

on:
  push:
    branches:
      - backend_services
  pull_request:
    branches:
      - backend_services

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 80:80
          - 8080:8080

    env:
      DB: ${{ secrets.DB }}
      PORT: ${{ secrets.PORT }}
      SECRET: ${{ secrets.SECRET }}
      GITHUB_ACTIONS: true
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create 'web' network
        run: docker network create web || true
      
      - name: Build and push Docker images
        run: docker-compose build

      - name: Deploy with docker-compose
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 45

      - name: Validate deployment
        run: |
          curl -I http://localhost:80/auth/validate
          curl -I http://localhost:80/auth/verify

      - name: Clean up
        run: docker-compose down
